# Generated by Django 4.2.6 on 2023-11-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cast',
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.video')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.person')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='person',
            field=models.ManyToManyField(through='media.People', to='cast.person'),
        ),
    ]
